# LLMBroker 示例配置文件
# 复制此文件为 config.yaml 并修改相应的API密钥

server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "info"

models:
  # 示例：OpenAI GPT模型配置
  gpt-3.5-turbo:
    provider: "openai"
    model_name: "gpt-3.5-turbo"
    api_key: "your-openai-api-key-here"  # 替换为您的API密钥
    base_url: "https://api.openai.com/v1"
    default_params:
      temperature: 0.7
      max_tokens: 1000

  # 示例：Claude模型配置
  claude-3:
    provider: "claude"
    model_name: "claude-3-sonnet-20240229"
    api_key: "your-anthropic-api-key-here"  # 替换为您的API密钥
    base_url: "https://api.anthropic.com/v1"
    default_params:
      temperature: 0.7
      max_tokens: 1000

  # 示例：通义千问模型配置
  qwen:
    provider: "qwen"
    model_name: "qwen-turbo"
    api_key: "your-dashscope-api-key-here"  # 替换为您的API密钥
    base_url: "https://dashscope.aliyuncs.com/api/v1"
    default_params:
      temperature: 0.7
      max_tokens: 1000

proxy:
  default_model: "gpt-3.5-turbo"
  enable_parameter_injection: true
  enable_request_logging: true
  timeout: 60
